spring:
  datasource:
    jndi-name: java:jboss/datasources/macsysDS
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      format_sql: true
    hibernate:
      ddl-auto: none